// src/pages/NonSurgicalTreatments.vue
<script setup lang="ts">
import TreatmentPage from '@/components/TreatmentPage.vue';
</script>

<template>
  <TreatmentPage
    title="Non-Surgical Treatments"
    subtitle="Conservative options for pain relief and improved function"
    icon="💉"
    :description="[
      'Not every orthopaedic problem requires surgery. Dr. Bañuls offers a comprehensive range of non-surgical treatment options that can provide significant relief for many patients. His honest approach means he\'ll always recommend conservative treatment when it\'s likely to be effective.',
      'From targeted injections to structured rehabilitation programs, these treatments can address pain and improve function without the need for an operation. For some patients, non-surgical treatment may delay or even eliminate the need for surgery.',
      'Dr. Bañuls works closely with physiotherapists and other specialists to ensure you receive comprehensive care tailored to your specific needs and goals.'
    ]"
    :conditions="[
      'Early Arthritis',
      'Tendinitis',
      'Bursitis',
      'Mild Joint Pain',
      'Sports Injuries',
      'Muscle Strains',
      'Chronic Pain',
      'Post-Surgical Rehabilitation'
    ]"
    :procedures="[
      {
        title: 'Corticosteroid Injections',
        description: 'Targeted injections of anti-inflammatory medication directly into affected joints or soft tissues for rapid pain relief and reduced inflammation.'
      },
      {
        title: 'PRP (Platelet-Rich Plasma) Therapy',
        description: 'Using your own blood\'s healing factors to promote tissue repair and reduce pain in tendons, ligaments, and joints.'
      },
      {
        title: 'Hyaluronic Acid Injections',
        description: 'Viscosupplementation to improve joint lubrication and cushioning, particularly effective for knee arthritis.'
      },
      {
        title: 'Physical Therapy Programs',
        description: 'Structured rehabilitation programs designed to strengthen muscles, improve flexibility, and restore function without surgery.'
      }
    ]"
    :benefits="[
      'Avoid surgery when possible',
      'Minimal downtime',
      'Lower risk than surgical options',
      'Can be repeated if needed',
      'Quick pain relief',
      'Honest assessment of likely outcomes'
    ]"
    :relatedTreatments="[
      { title: 'Knee Surgery', href: '/treatments/knee-surgery' },
      { title: 'Hip Replacement Surgery', href: '/treatments/hip-replacement' },
      { title: 'Spine Surgery', href: '/treatments/spine-surgery' }
    ]"
  />
</template>

// src/pages/NonSurgicalTreatments.tsx
import TreatmentPage from '@/components/TreatmentPage';

const NonSurgicalTreatments = () => {
  return (
    <TreatmentPage
      title="Non-Surgical Treatments"
      subtitle="Conservative options for pain relief and improved function"
      icon="💉"
      description={[
        "Not every orthopaedic problem requires surgery. Dr. Bañuls offers a comprehensive range of non-surgical treatment options that can provide significant relief for many patients. His honest approach means he'll always recommend conservative treatment when it's likely to be effective.",
        "From targeted injections to structured rehabilitation programs, these treatments can address pain and improve function without the need for an operation. For some patients, non-surgical treatment may delay or even eliminate the need for surgery.",
        "Dr. Bañuls works closely with physiotherapists and other specialists to ensure you receive comprehensive care tailored to your specific needs and goals."
      ]}
      conditions={[
        "Early Arthritis",
        "Tendinitis",
        "Bursitis",
        "Mild Joint Pain",
        "Sports Injuries",
        "Muscle Strains",
        "Chronic Pain",
        "Post-Surgical Rehabilitation"
      ]}
      procedures={[
        {
          title: "Corticosteroid Injections",
          description: "Targeted injections of anti-inflammatory medication directly into affected joints or soft tissues for rapid pain relief and reduced inflammation."
        },
        {
          title: "PRP (Platelet-Rich Plasma) Therapy",
          description: "Using your own blood's healing factors to promote tissue repair and reduce pain in tendons, ligaments, and joints."
        },
        {
          title: "Hyaluronic Acid Injections",
          description: "Viscosupplementation to improve joint lubrication and cushioning, particularly effective for knee arthritis."
        },
        {
          title: "Physical Therapy Programs",
          description: "Structured rehabilitation programs designed to strengthen muscles, improve flexibility, and restore function without surgery."
        }
      ]}
      benefits={[
        "Avoid surgery when possible",
        "Minimal downtime",
        "Lower risk than surgical options",
        "Can be repeated if needed",
        "Quick pain relief",
        "Honest assessment of likely outcomes"
      ]}
      relatedTreatments={[
        { title: "Knee Surgery", href: "/treatments/knee-surgery" },
        { title: "Hip Replacement Surgery", href: "/treatments/hip-replacement" },
        { title: "Spine Surgery", href: "/treatments/spine-surgery" }
      ]}
    />
  );
};

export default NonSurgicalTreatments;
